### ISSUE TITLE
Crash on save of new Respondent

### ISSUE THREAD

**Issue by Archie-C** [DigitalNutritionalAssessment/gibsonify#70]
Saving the Name and number only
Name: Josh
Number: 7555555555

**Comment by Archie-C** [comment]
Bad state: Cannot add new events after calling close

Stack Trace:
 _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      Bloc.add (package:bloc/src/bloc.dart:99:24)
#2      HouseholdsBloc._onHouseholdsPageOpened.<anonymous closure> (package:gibsonify/households/bloc/households_bloc.dart:27:7)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
